# -*- coding: utf-8 -*-
"""aula 18/03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eeB92zopJHUbK5ZHEFQdkU0sLy42X0gs
"""

nota = 7
nota = "aula"
_nota = 3
nota_aluno = 3
# variavel composta - lista
aluno = [1,2,4.53,"programação",["ana","Pedro","clara"]]
nota_1 = 6
nota_2 = 7
nota_3 = 6
media = 0
media = media + (nota_1 + nota_2 + nota_3)/3
media += (nota_1 + nota_2 + nota_3)/3 #mesma coisa de cima (contração)
nota_2 >= nota_1
nota_2 <= nota_1
nota_2 == nota_1
nota_2 != nota_1
verdade = True
not verdade # inverte o de cima
if (media >= 6):
 print("aprovado")
elif (media < 1): # jogar tudo para esquerda para simplificar e nao repetir if
  print("reprovado")
else:
  print("AF")

nota_A1 = 4.3
nota_A2 = 5.8
media = (nota_A1 + nota_A2)
if (media >= 6):
 print("Aprovado")
elif (media < 1):
 print("Reprovado")
else:
 print("AF")

nota_1 = 6
nota_2 = 7
nota_1 != nota_2

contador = 0
while (contador <11):    # while = enquanto.
 print("Contador:", contador)
 contador += 1 #contador = contador +1
print("Contador:", contador)

#1. Crescimento de capital com juros compostos
import matplotlib.pyplot as plt #as significa dar um apelido (matplotlib.pyplot para plt)
capital = 1000
taxa = 0.02
meses = 24
valores = []
for m in range(meses): #for parecido o while,in = entrar/está dentro.range intervalo
 capital = capital * (1 + taxa)
 valores.append(capital) #apped = incluir
plt.plot(valores)
plt.title("Crescimento do investimento")
plt.xlabel("Meses")
plt.ylabel("Capital (R$)")
plt.show() #show = desenhar

a = 8
b = 2
def soma(a,b):
 resultado = a + b
print(resultado)
 return resultado