# -*- coding: utf-8 -*-
"""atividades

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3K5_G4O7wGACnEgqVTNrlOxTMLNaPbm
"""

a = 10
b = 5
soma = a + b
subtracao = a - b
multiplicacao = a * b
divisao = a / b
print("Soma:", soma)
print("Subtração:", subtracao)
print("Multiplicação:", multiplicacao)
print("Divisão:", divisao)

idade = 18
if idade >= 18:
 print("Maior de idade")
else:
 print("Menor de idade")

for i in range(1,6):
 print(i)

contador = 6
while contador <= 5:
 print("Contador:", contador)
 contador += 1
print ("contador:", contador)

def soma(a, b):
 resultado = a + b
 return resultado
print(soma(3, 7))

numeros = [10, 20, 30, 40]
print("Primeiro elemento:", numeros[0])
for n in numeros:
 print(n)

aluno = {
"nome": "Carlos",
"idade": 21,
"curso": "Ciência de Dados"
}
print(aluno["nome"])
print(aluno["curso"])

texto = "Python para Ciência de Dados"
print(texto.upper())
print(texto.lower())
print(len(texto))

nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
print("Nome:", nome)
print("Idade:", idade)

import numpy as np
vetor = np.array([1, 2, 3, 4, 5])
print("Vetor:", vetor)
print("Média:", np.mean(vetor))
print("Desvio padrão:", np.std(vetor)) #nao entendi qual a diferença entre os codigos mean,std e np.

#parte 2

numeros = [10,20,30,40,50]
print(numeros)

frutas = ["maçã","banana","laranja"]
print(frutas[0])
print(frutas[1])
print(frutas[2])

nomes = ("ana","carlos","maria","joão")
for nome in nomes:
 print(nome)

numeros = [1,2,3]
numeros.append(4)
numeros.append(5)
print(numeros)

cores = ["vermelho","azul","verde","amarelo"]
cores.remove("verde")
print(cores)

numeros = [5,10,15,20]
soma = sum(numeros)
print(soma)

valores = (23,45,12,67,34)
print("maximo valor:",max(valores))
print("minimo valor:",min(valores))

numeros = [9,3,7,1,5]
numeros.sort()
print(numeros)

lista = list(range(1,11))
print(lista)

matriz = [[1,2,3],[4,5,6],[7,8,9]]
print(matriz[0][1])
print(matriz[2][2])

#parte 3
numeros = [10,20,30,40]
numeros.insert(2,25) #posição 2 recebe o valor 25
print(numeros)

lista1 = [1,2,3]
lista2 = [4,5,6]
lista1.extend(lista2)
print(lista1)

nome = ["Ana","Carlos","Maria","João"]
removido = nome.pop(1)
print("removido:", removido)
print("lista:",nome)

cores = ["vermelho","azul","verde","amarelo"]
posicao = cores.index("verde")
print("Posição:", posicao)

numeros = [1,2,2,3,4,2,5]
quantidade = numeros.count(2)
print("o numeros 2 aparece:",quantidade,"vezes")

numeros = [10,20,30,40]
numeros.reverse()
print(numeros)

lista_original = [1,2,3]
lista_copia = lista_original.copy()
print("lista original:", lista_original)
print("lista copia:", lista_copia)

dados = [5,10,15,20]
dados.clear()
print(dados)

numeros = [10,20,30,40,50]
sublista = numeros[1:4]
print(sublista)

quadrados = [x**2 for x in range(1,6)]
print(quadrados)

# exemplos - Python - for com in - while.docx

n = 5
fatorial = 1
for i in range(1, n+1):
 fatorial = fatorial * i
print("Fatorial:", fatorial)

s0 = 0
v = 10
a = 2
for t in range(0, 11):
 s = s0 + v*t + 0.5*a*t**2
 print("Tempo:", t, "Posição:", s)

h0 = 100
g = 9.81
for t in range(0, 6):
 h = h0 - 0.5*g*t**2
 print("Tempo:", t, "Altura:", h)

capital = 1000
taxa = 0.05
for ano in range(1, 11):
 montante = capital * (1 + taxa*ano)
 print("Ano:", ano, "Montante:", montante)

capital = 1000
taxa = 0.05
montante = capital
for ano in range(1, 11):
 montante = montante * (1 + taxa)
 print("Ano:", ano, "Montante:", montante)

populacao = 1000
taxa = 0.02
for ano in range(1, 21):
 populacao = populacao * (1 + taxa)
 print("Ano:", ano, "População:", int(populacao)) #int considera so os numeros inteiros

massa = 2
for v in range(0, 21, 2):
 energia = 0.5 * massa * v**2
 print("Velocidade:", v, "Energia:", energia)

saldo = 0
deposito = 500
taxa = 0.01
for mes in range(1, 13):
 saldo = (saldo + deposito) * (1 + taxa)
 print("Mês:", mes, "Saldo:",int(saldo))

capital = 1000
meta = 2000
taxa = 0.02
mes = 0
while capital < meta:
 capital = capital * (1 + taxa)
 mes += 1
print("Meses necessários:", mes)
print("Valor final:", capital)

capital = 5000
objetivo = capital * 2
taxa = 0.05
anos = 0
while capital < objetivo:
 capital = capital * (1 + taxa)
 anos += 1
print("Anos para dobrar o capital:", anos)

saldo = input("Digite o saldo da conta: ")
deposito = input("Digite o valor do depósito: ")
objetivo = input("Digite o valor desejado: ")
saldo = float(saldo)
deposito = float(deposito)
objetivo = float(objetivo) # float para numeros decimais e int para inteiros
meses = 0
while saldo < objetivo:
  saldo = saldo + deposito
  meses += 1
print("Meses necessários:", meses , "saldo atual",saldo)

divida = 5000
juros = 0.03
pagamento = 600
meses = 0
while divida > 0:
  divida = divida * (1 + taxa) - pagamento
  meses += 1
print("quantidade de meses até quitar a divida:",meses)

saldo = 0
deposito = 200
taxa = 0.015
objetivo = 20000
mes = 0
while saldo < objetivo:
  saldo = (saldo + deposito) * (1 + taxa)
  mes += 1
print("Meses necessários:", mes)
print("saldo:",int(saldo))

preco = 1000
taxa = 0.04
anos = 0
while preco < 2000:
 preco = preco * (1 + taxa)
 anos += 1
print("Anos:", anos)
print("Preço final:", preco)

saldo = 10000
retirada = 800
mes = 0
while saldo > 0:
 saldo = saldo - retirada
 mes += 1
print("Meses até zerar:", mes)

saldo = 0
aporte = 1000
taxa = 0.008
mes = 0
while saldo < 500000:
 saldo = (saldo + aporte) * (1 + taxa)
 mes += 1
print("Meses:", mes)
ano = mes / 12
print("Ano:", int(ano))
print("Saldo final:", saldo)

divida = 20000
juros = 0.02
pagamento = 900
mes = 0
while divida > 0:
 divida = divida * (1 + juros)
 divida = divida - pagamento
 mes += 1
print("Meses necessários:", mes)

patrimonio = 50000
taxa = 0.06
anos = 0
while patrimonio < 100000:
 patrimonio = patrimonio * (1 + taxa)
 anos += 1
print("Anos necessários:", anos)