# -*- coding: utf-8 -*-
"""aula13/05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E9pQvZOAK6HU04nbY4KNO1mgj_eIuO23
"""

html = """
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Artigo Cientifico - Meteorito Fe-Ni</title>
    <style>
       body{
           font-family: Arial, sans-serif;
           background-color: #f4f4f4;
           margin: 0;
           padding: 0;
       }
       .container{
           width: 80%;
           margin: auto;
           background: white;
           padding: 30px;
           margin-top: 40px;
           box-shadow: 0px 0px 10px rgba(0,0,0,0.2);
           border-radium: 10px;
       }
       h1{
           color: #1f4e79;
           text-align: center;
       }
       h2{
           color: #0b5394;
           border-bottom: 2px solid #0b5394;
           padding-bottom: 5px;
       }
       p{
          text-align: justify;
          line-height: 1.8;
       }
       .footer{
          margin-top: 30px;
          text-align: center;
          color: gray;
          font-size: 14px;
       }
    </style>
</head>
<body>
<div class="container">
      <h1>Caracterização Microestrutural de Meteorito Fe-Ni</h1>
      <h2>Resumo</h2>
      <p>
      Este trabalho apresenta uma análise microestrutural e composicional...
      </p>
      <h2>Resultados</h2>
      <p>
      A difração ...
      </p>
      <h2>Conclusão</h2>
      <p>
      O resultados confirmam...
      </p>
      <div class="footer">
        Página html gerada no python.
      </div>
</div>
</body>
</html>
"""
with open("pagina_meteorito.html","w", encoding="utf-8") as arquivo:
    arquivo.write(html)
print("Arquivo HTML criado com sucesso!")
from IPython.display import display, HTML
display(HTML(html))