# -*- coding: utf-8 -*-
"""Problemas de finança

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fW9NWrLE_QQexqo3Va39BL7XOFODOymP
"""

# Crescimento de capital com juros compostos
import matplotlib.pyplot as plt
capital = 1000
taxa = 0.02
meses = 24
valores = []
for m in range(meses):
 capital = capital * (1 + taxa)
 valores.append(capital)
plt.plot(valores)
plt.title("Crescimento do investimento")
plt.xlabel("Meses")
plt.ylabel("Capital (R$)")
plt.show()

# 2 Evolução de poupança mensal
import matplotlib.pyplot as plt
saldo = 0
deposito = 500
meses = 24
historico = []
for m in range(meses):
 saldo += deposito
 historico.append(saldo)
plt.plot(historico)
plt.title("Acúmulo de poupança")
plt.xlabel("Meses")
plt.ylabel("Saldo")
plt.grid(True,alpha=0.6)# eu adicionei a parte, o alpha serve para diminuir ou aumentar a opacidade das linhas do grid
plt.show()

# 3. Investimento com aportes + juros
import matplotlib.pyplot as plt
saldo = 0
aporte = 300
taxa = 0.01
historico = []
for mes in range(36):
 saldo = (saldo + aporte) * (1 + taxa)
 historico.append(saldo)
plt.plot(historico)
plt.title("Investimento com aportes")
plt.show()

# 4. Comparação: juros simples vs compostos
import matplotlib.pyplot as plt
capital = 1000
taxa = 0.05
simples = []
compostos = []
valor_composto = capital
for ano in range(10):
 simples.append(capital * (1 + taxa*ano))
 valor_composto = valor_composto * (1 + taxa)
 compostos.append(valor_composto)
plt.plot(simples)
plt.plot(compostos)
plt.legend(["Juros Simples", "Juros Compostos"])
plt.title("Comparação de Juros")
plt.show()

#5. Simulação de inflação
import matplotlib.pyplot as plt
preco = 100
taxa = 0.04
historico = []
for ano in range(20):
 preco = preco * (1 + taxa)
 historico.append(preco)
plt.plot(historico)
plt.title("Impacto da inflação")
plt.show()

# 6. Redução de dívida
import matplotlib.pyplot as plt
divida = 10000
pagamento = 800
juros = 0.02
historico = []
while divida > 0:
 divida = divida*(1+juros) - pagamento
 historico.append(divida)
plt.plot(historico)
plt.title("Pagamento da dívida")
plt.show()

# 7. Patrimônio acumulado ao longo do tempo
import matplotlib.pyplot as plt
patrimonio = 0
aporte = 1000
taxa = 0.01
historico = []
for mes in range(120):
 patrimonio = (patrimonio + aporte)*(1+taxa)
 historico.append(patrimonio)
plt.plot(historico)
plt.title("Crescimento do patrimônio")
plt.show()

# 8. Investimento com diferentes taxas
import matplotlib.pyplot as plt
capital = 1000
taxas = [0.01,0.02,0.03]
for taxa in taxas:
 valor = capital
 historico = []
 for mes in range(36):
  valor = valor*(1+taxa)
  historico.append(valor)
 plt.plot(historico)
plt.legend(["1%","2%","3%"])
plt.title("Comparação de taxas")
plt.show()

#9. Simulação de crescimento salarial
import matplotlib.pyplot as plt
salario = 3000
taxa = 0.05
historico = []
for ano in range(20):
 salario = salario*(1+taxa)
 historico.append(salario)
plt.plot(historico)
plt.title("Crescimento salarial")
plt.show()

# 10. Evolução do preço de um ativo
import matplotlib.pyplot as plt
import random # biblioteca de um dado(sorteio)
preco = 100
historico = []
for dia in range(100):
 variacao = random.uniform(-0.02,0.02)
# A função(uniform) onde sorteia um numero entre o valor A e o valor B, ou seja (-2%) a (2%).
 preco = preco*(1+variacao)
 historico.append(preco)
plt.plot(historico)
plt.title("Simulação de preço de ativo")
plt.show()

# 11. Acúmulo para aposentadoria
import matplotlib.pyplot as plt
saldo = 0
aporte = 1500
taxa = 0.008
historico = []
for mes in range(360):
 saldo = (saldo+aporte)*(1+taxa)
 historico.append(saldo)
plt.plot(historico)
plt.title("Aposentadoria")
plt.show()

# 12. Crescimento de investimento anual
import matplotlib.pyplot as plt
capital = 5000
taxa = 0.06
historico = []
for ano in range(30):
 capital = capital*(1+taxa)
 historico.append(capital)
plt.plot(historico)
plt.title("Investimento de longo prazo")
plt.show()

# 13. Comparação de dois investimentos
import matplotlib.pyplot as plt
inv1 = 1000
inv2 = 1000
taxa1 = 0.01 # 1
taxa2 = 0.015 # 1.5
h1=[]
h2=[]
for mes in range(60):
 inv1 = inv1*(1+taxa1)
 inv2 = inv2*(1+taxa2)
 h1.append(inv1)
 h2.append(inv2)
plt.plot(h1)
plt.plot(h2)
plt.legend(["Investimento A","Investimento B"])
plt.show()

#14. Crescimento do custo de vida
import matplotlib.pyplot as plt
custo = 2000
inflacao = 0.03
historico = []
for ano in range(25):
 custo = custo*(1+inflacao)
 historico.append(custo)
plt.plot(historico)
plt.title("Custo de vida")
plt.show()

# 15. Amortização de empréstimo
import matplotlib.pyplot as plt
divida = 15000
pagamento = 1000
juros = 0.015
historico = []
while divida > 0:
 divida = divida*(1+juros) - pagamento
 historico.append(divida)
plt.plot(historico)
plt.title("Amortização")
plt.show()

# 16. Investimento com crescimento variável
import matplotlib.pyplot as plt
import random
capital = 1000
historico=[]
for ano in range(20):
 taxa = random.uniform(0.03,0.08)
 capital = capital*(1+taxa)
 historico.append(capital)
plt.plot(historico)
plt.title("Investimento variável")
plt.show()

#17. Evolução do valor de imóvel
import matplotlib.pyplot as plt
valor = 200000
taxa = 0.04
historico=[]
for ano in range(30):
 valor = valor*(1+taxa)
 historico.append(valor)
plt.plot(historico)
plt.title("Valorização de imóvel")
plt.show()

# 18. Projeção de fundo de investimento
import matplotlib.pyplot as plt
saldo = 10000
taxa = 0.01
historico=[]
for mes in range(120):
 saldo = saldo*(1+taxa)
 historico.append(saldo)
plt.plot(historico)
plt.title("Fundo de investimento")
plt.show()

# 19. Evolução do patrimônio líquido
import matplotlib.pyplot as plt
patrimonio = 50000
taxa = 0.07
historico=[]
for ano in range(20):
 patrimonio = patrimonio*(1+taxa)
 historico.append(patrimonio)
plt.plot(historico)
plt.title("Patrimônio líquido")
plt.show()

# 20. Simulação de carteira de investimentos
import matplotlib.pyplot as plt
import random
valor = 10000
historico=[]
for mes in range(60):
 retorno = random.uniform(-0.03,0.05)
 valor = valor*(1+retorno)
 historico.append(valor)
plt.plot(historico)
plt.title("Carteira de investimentos")
plt.show()