# -*- coding: utf-8 -*-
"""1-lista de exercícios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13VuNwAwFGJZfPzMjAUKijWL00UDvPI3f
"""

import math
def r(t):
    """Define a função da taxa de juros variável."""
    return 0.05 + 0.01 * t

def regra_trapézio(f, a, b):
    """Aplica a regra do trapézio simples."""
    return (b - a) * (f(a) + f(b)) / 2
# Dados do exercício
P = 1000
a = 0
b = 2
# 1. Calcular a integral da taxa
integral_taxa = regra_trapézio(r, a, b)
# 2. Calcular o montante final
montante = P * math.exp(integral_taxa)
print(f"Resultado da Integral (Taxa Acumulada): {integral_taxa:.4f}")
print(f"Montante Final M(2): R$ {montante:.2f}")

import math

def r_quadratica(t):
    """Taxa r(t) = 0.04 + 0.02 * t^2"""
    return 0.04 + 0.02 * (t**2)

def regra_simpson(f, a, b):
    """Aplica a Regra de Simpson 1/3 simples."""
    m = (a + b) / 2  # Ponto médio
    h = (b - a) / 2  # Passo
    return (h / 3) * (f(a) + 4*f(m) + f(b))

# Dados
P = 1000
t_inicio = 0
t_fim = 2

# Processamento
integral_taxa = regra_simpson(r_quadratica, t_inicio, t_fim)
montante = P * math.exp(integral_taxa)

print(f"--- Exercício 2: Simpson ---")
print(f"Integral da taxa: {integral_taxa:.4f}")
print(f"Montante Final: R$ {montante:.2f}")

import math

def regra_trapezio_composta(valores_y, h):
    """
    Calcula a integral usando a regra do trapézio composta
    com base em uma lista de valores pré-calculados.
    """
    soma = valores_y[0] + valores_y[-1] # Primeiro + Último
    soma += 2 * sum(valores_y[1:-1])    # 2x os valores do meio
    return (h / 2) * soma

# Dados do exercício
P = 1000
h = 1
taxas = [0.05, 0.058, 0.059, 0.051] # Valores de r(t) fornecidos

# Processamento
integral_taxa = regra_trapezio_composta(taxas, h)
montante = P * math.exp(integral_taxa)

print(f"--- Exercício 3: Trapézio Composto ---")
print(f"Integral da taxa (acumulada): {integral_taxa:.4f}")
print(f"Montante Final M(3): R$ {montante:.2f}")

import math

def r_exponencial(t):
    """Taxa r(t) = 0.03 * e^(0.1 * t)"""
    return 0.03 * math.exp(0.1 * t)

def regra_simpson_simples(f, a, b):
    """Aplica a regra de Simpson 1/3 com 3 pontos."""
    h = (b - a) / 2
    m = (a + b) / 2
    return (h / 3) * (f(a) + 4*f(m) + f(b))

# Configurações
P = 1000
t0, t2 = 0, 2

# Cálculo
integral_taxa = regra_simpson_simples(r_exponencial, t0, t2)
montante = P * math.exp(integral_taxa)

print(f"--- Exercício 4: Simpson (Exponencial) ---")
print(f"Integral da taxa: {integral_taxa:.6f}")
print(f"Montante Final: R$ {montante:.2f}")

# Comparação com valores da tabela (arredondados)
tabela_y = [0.03, 0.033, 0.036]
integral_tabela = (1/3) * (tabela_y[0] + 4*tabela_y[1] + tabela_y[2])
montante_tabela = P * math.exp(integral_tabela)
print(f"Montante usando valores da tabela: R$ {montante_tabela:.2f}")

import math

def calcular_exercicio_5_logistica():
    # Capital inicial
    P = 1000
    h = 1

    # Valores da tabela fornecida (r(0), r(1), r(2))
    taxas = [0.04, 0.058, 0.070]

    # Regra do Trapézio Composta
    # (h/2) * (primeiro + 2*soma_meio + ultimo)
    soma_interna = sum(taxas[1:-1])
    integral = (h / 2) * (taxas[0] + 2 * soma_interna + taxas[-1])

    # Cálculo do Montante
    montante = P * math.exp(integral)

    print(f"--- Exercício 5: Trapézio (Logística) ---")
    print(f"Integral da taxa (acumulada): {integral:.3f}")
    print(f"Montante Final: R$ {montante:.2f}")

calcular_exercicio_5_logistica()

import math

def calcular_exercicio_6_taxa_cubica():
    # Capital inicial
    P = 1000
    h = 1

    # Valores da tabela fornecida pelo professor
    # r(0)=0.03, r(1)=0.032, r(2)=0.046
    taxas = [0.03, 0.032, 0.046]

    # Regra de Simpson 1/3 simples
    # (h/3) * (f(a) + 4*f(m) + f(b))
    integral = (h / 3) * (taxas[0] + 4 * taxas[1] + taxas[2])

    # Cálculo do Montante
    montante = P * math.exp(integral)

    print(f"--- Exercício 6: Simpson (Cúbica) ---")
    print(f"Integral da taxa: {integral:.4f}")
    print(f"Montante Final: R$ {montante:.2f}")

calcular_exercicio_6_taxa_cubica()

import math

def calcular_exercicio_7_taxa_decrescente():
    # Capital inicial
    P = 1000
    h = 1

    # Valores da tabela fornecida pelo professor
    taxas = [0.06, 0.05, 0.04, 0.03]

    # Regra do Trapézio Composta
    # (h/2) * (primeiro + 2*soma_meio + ultimo)
    soma_interna = sum(taxas[1:-1])
    integral = (h / 2) * (taxas[0] + 2 * soma_interna + taxas[-1])

    # Cálculo do Montante
    montante = P * math.exp(integral)

    print(f"--- Exercício 7: Trapézio (Decrescente) ---")
    print(f"Integral da taxa: {integral:.3f}")
    print(f"Montante Final: R$ {montante:.2f}")

calcular_exercicio_7_taxa_decrescente()

import math

def calcular_exercicio_8_ciclo_economico():
    # Capital inicial
    P = 1000
    h = 1

    # Valores da tabela fornecida pelo professor
    taxas = [0.07, 0.061, 0.042]

    # Regra de Simpson 1/3
    integral = (h / 3) * (taxas[0] + 4 * taxas[1] + taxas[2])

    # Cálculo do Montante
    montante = P * math.exp(integral)

    print(f"--- Exercício 8: Simpson (Cosseno) ---")
    print(f"Integral da taxa (acumulada): {integral:.6f}")
    print(f"Montante Final: R$ {montante:.2f}")

calcular_exercicio_8_ciclo_economico()

import math

def calcular_exercicio_9_taxa_polinomial():
    # Capital inicial
    P = 1000
    h = 1

    # Valores da tabela fornecida pelo professor
    taxas = [0.04, 0.055, 0.08]

    # Regra do Trapézio Composta
    soma_interna = sum(taxas[1:-1])
    integral = (h / 2) * (taxas[0] + 2 * soma_interna + taxas[-1])

    # Cálculo do Montante
    montante = P * math.exp(integral)

    print(f"--- Exercício 9: Trapézio (Polinomial) ---")
    print(f"Integral da taxa: {integral:.3f}")
    print(f"Montante Final: R$ {montante:.2f}")

calcular_exercicio_9_taxa_polinomial()

import math

def calcular_exercicio_10_taxa_oscilatoria():
    # Capital inicial
    P = 1000
    h = 1

    # Valores da tabela fornecida pelo professor
    taxas = [0.05, 0.051, 0.048]

    # Regra de Simpson 1/3
    integral = (h / 3) * (taxas[0] + 4 * taxas[1] + taxas[2])

    # Cálculo do Montante
    montante = P * math.exp(integral)

    print(f"--- Exercício 10: Simpson (Oscilatória) ---")
    print(f"Integral da taxa: {integral:.6f}")
    print(f"Montante Final: R$ {montante:.2f}")

calcular_exercicio_10_taxa_oscilatoria()

r = [0.05, 0.058, 0.059, 0.051]; h = 1
integral = (h / 2) * (r[0] + 2*sum(r[1:-1]) + r[-1])
montante = 1000 * math.exp(integral)
print(f"montante R$ {montante:.2f}")