# -*- coding: utf-8 -*-
"""atividades 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4A2IGdVX28N3CH8LfzAod2IE6_NzblH
"""

# parte 1 operações basicas
numeros = [10,20,30,40,50]
print(numeros)

numeros = [10,20,30,40,50]
soma = sum(numeros)
print(soma)

numeros = [5,8,25,41,36]
print("maior valor:", max(numeros))

numeros = [25,32,15,24,61]
print("menor valor:", min(numeros))

numeros = [10,15,20,25,30]
media = sum(numeros)/len(numeros)
print(media)

#parte 2 manipulando lista
numeros = [4,8,12,16,20]
numeros.append(24)
print(numeros)

numeros = [10,20,30,50]
numeros.insert(3,40)
print(numeros)

frutas = ["maça","banana","laranja"]
frutas.remove("banana")
print(frutas)

frutas = ["maça","banana","laranja"]
frutas.pop(2)
print(frutas)

numeros = [2,5,8,10,6,9]
numeros.clear()
print(numeros)

#parte 3 percorrendo listas
frutas = ["maça","banana","laranja"]
for fruta in frutas:
    print(fruta)

numeros = [5,10,15,20,25]
resultado = [x*2 for x in numeros]
print(resultado)

numeros = [2,3,5,6,7,9,10]
pares = [x for x in numeros if x%2 == 0]
print("numeros pares:",pares)

numeros = [2,8,12,25,8]
maior = [x for x in numeros if x > 10]
print("maiores que 10:", maior)

numeros = [-1,2,14,21,8]
quantos = [x for x in numeros if x > 0]
print("quantos numeros positivos:", len(quantos))

#parte 4 ordenação e busca
numeros = [5,2,8,1,9]
numeros.sort()
print(numeros)

numeros = [1,6,4,3,8,2,15]
numeros.sort(reverse=True)
print(numeros)

numeros = [1,2,3,4,5,6,7,8,9]
if 5 in numeros:
  print("5 está na lista")
else:
  print("5 não está na lista")

numeros = [5,10,15,20,25]
print(numeros.index(10))

numeros = [1,2,3,2,5,2,7,8,9]
print(numeros.count(2))

#Parte 5 — Listas mais avançadas
lista = [1,2,3,4]
lista.reverse()
print(lista)

#22. Criar lista com números de 1 a 20
lista = list(range(1,21))
print(lista)

#23. Criar lista com quadrados
quadrados = [x**2 for x in range(1,11)]
print(quadrados)

#24. Criar lista apenas com números ímpares
impares = [x for x in range(1,21) if x % 2 != 0] # x % 2 significa "divisao"
print(impares)

#25. Concatenar duas listas
lista1 = [1,2,3]
lista2 = [4,5,6]
lista3 = lista1 + lista2
print(lista3)

#Parte 6 — Estruturas com listas
#26. Lista de listas (matriz)
matriz = [
[1,2,3],
[4,5,6],
[7,8,9]
]
print(matriz[1][2])

#27. Somar todos os elementos da matriz
matriz = [
[1,2],
[3,4]
]
soma = 0
for linha in matriz:
 for valor in linha:
  soma += valor
print(soma)

#28. Achatar matriz (flatten)
matriz = [[1,2],[3,4],[5,6]]
lista = [item for sublista in matriz for item in sublista]
print(lista)

#29. Encontrar números duplicados
lista = [1,2,3,2,4,5,1]
duplicados = []
for x in lista:
 if lista.count(x) > 1 and x not in duplicados:
  duplicados.append(x)
print(duplicados)

#30. Remover duplicados
lista = [1,2,2,3,4,4,5]
lista_unica = list(set(lista))
print(lista_unica)