# -*- coding: utf-8 -*-
"""aula 22/04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXeP24LYaUe7m8ej5yWaYHOiqbo86CN9
"""

with open("dados.txt","w") as f:
  f.write("Francisco")
with open("dados.txt","w") as f:
  f.write("programação")
with open("dados.txt","a") as f:
 f.write("\nidade:25"+"\ncep:025543000"+"\ncel:325440008")
with open("dados.txt","r") as f:
  print(f.read())
with open("dados.txt","r") as f:
  conteudo = f.read()
  print(len(conteudo))
with open("dados.txt","r") as f:
  linhas = f.readlines() #quantas linhas
  print(len(linhas))
with open("dados.txt","r") as f:
  palavras = f.read().split()
  print(len(palavras))
with open("dados.txt","r") as f:
  print((f.read().upper()))
busca = "idade"
with open("dados.txt","r") as f:
  if busca in f.read():
    print("encontrado")

arquivo = open("palavras.txt","w")
arquivo.write('banana'+"\n")
arquivo.write('melancia'+"\n")
arquivo.write('banana'+"\n")
arquivo.write('melancia'+"\n")
arquivo.write('morango'+"\n")
arquivo.write('manga'+"\n")
arquivo.close()
arquivo = open('palavras.txt','r')
for linha in arquivo:
  print(linha)
arquivo.close()
try:
 arquivo = open('palavras.txt','r')
 palavra = []
 for linha in arquivo:
   linha = linha.strip()
   palavra.append(linha)
 print(palavra)
 arquivo.close()
except:
  print("arquivo não existe")
  arquivo.close()

arquivo = open("palavras.txt","w")
arquivo.write('banana'+"\n")
arquivo.write('melancia'+"\n")
arquivo.write('banana'+"\n")
arquivo.write('melancia'+"\n")
arquivo.write('morango'+"\n")
arquivo.write('manga'+"\n")
arquivo.close()
arquivo = open('palavras.txt','r')
for linha in arquivo:
  print(linha)
arquivo.close()
arquivo = open('palavras.txt','r')
palavra = []
for linha in arquivo:
   linha = linha.strip()
   palavra.append(linha)
print(palavra)
arquivo.close()
dict =  ("Assis","25","cep:12543000") #nao entendi
tuple = ("Assis","25","cep:12543000") #nao entendi

import datetime
# função para ler o conteúde do arquivo
def ler_arquivo():
  try:
    with open("registro.txt", "r") as arquivo:
      conteudo = arquivo.read()
      print("Conteudo Anual:")
      print(conteudo)
  except FileNotFoundError:
    print("O arquivo não foi criado.")

#Função para escrever no arquivo
def escrever_arquivo():
  with open("registro.txt", "w") as arquivo:
    mensagem = "registro inicial:{}".format(datetime.datetime.now())
    arquivo.write(mensagem)
    print("Registro escrito com sucesso!")
#Função para adicionar conteúdo ao arquivo

def adicionar_conteudo():
  with open("registro.txt", "a") as arquivo:
    mensagem = "\nAtualização:{}".format(datetime.datetime.now())
    arquivo.write(mensagem)
    print("Conteúdo adicionado com sucesso!")

#Execução do exemplo
def main():
 ler_arquivo()
 escrever_arquivo()
 adicionar_conteudo()
 ler_arquivo()
main()

def calcular_fatorial(n):
  if n < 0:
   return "ser positivo"
  elif n == 0 or n == 1:
    return 1
  else:
    fatorial = 1
    for i in range(2, n + 1):
      fatorial *= i
    return fatorial

n = 5
m = calcular_fatorial(n)
print(m)

def f(x):
  return x * x
print(f(3)+f(4))