# -*- coding: utf-8 -*-
"""aula15/04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3D9ojpNogQhLtGn2LrKOoxuZ3bRUaQ4
"""

L = [0,1,2,3,4,5,6,7,8,9]
#nivel 1
L[0:5]
L[2:7]
L[:4]
L[5:]
#NIVEL 2 - COM PASSO
L[:]
L[0:10:2]
L[1:10:2]
L[2:9:3]
L[0:10:4]
#niveL 3 indice negatvo/// ele sempre começa da esquerda para a direta
L[-1]
L[-5]
L[:-3]
L[-7:-2]
L[-8:-1:2]
L[-5:-1]
#NIVEL 4 - INVERSÃO
L[::-1]
L[::-2]
L[8:2:-1] #PESQUISAR DEPOIS
#NIVEL 5 - CASOS MISTOS
L[1:-1]
L[2:-2:2]
L[-1:-8:-2]
L[-2::-2]
L[::3]
#NIVEL 6 - APLICAÇÕES REAIS
#pares
pares = L[::2]
#impares
impares = L[1::2]
#ultimos invertidos
L[:-4:-1]
#SUBLISTA CENTRAL
L[len(L)//4:3*len(L)//4]

def main():
  A=cria_matriz()
  imprime_matriz(A)

def cria_matriz():
  '''nome->matriz Pede informações para o usuario(numero de linhas, numero de colunas e os elementos) e retorna uma matriz com essas caracteristcas'''
  n_linhas=int(input("Digite o numero de linhas:"))
  n_colunas=int(input("Digite o numero de colunas:"))
  matriz=[]
  for i in range(n_linhas):
    linha=[]
    for j in range(n_colunas):
     print("digite o elemento(%d,%d):"%(i+1,j+1),end="")
   #'end' é ó pro print não pular a linha
     num=int(input())
     linha.append(num)
    matriz.append(linha)
  return matriz
#----------------------------------------------------
#Função que imprime a matriz
def imprime_matriz(matriz):
  '''Matriz->Nome Função que imprime uma matriz de forma legível'''
  m=len(matriz)
  n=len(matriz[0])
  for i in range(m):
    for j in range(n):
      print("%6d"%(matriz[i][j]),end="")#[linha][coluna]
#O 6 são os espaçs ocupados pelos numeros
    print()#para pular a linha
main()