# -*- coding: utf-8 -*-
"""jogo do bixo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KkEh4-rIfmkOLW0KUZHvS7jKwltsi7KD
"""

#Nome : Heitor Masaro Nakasato Cavallaro
# NUSP : 9299070
# Turma: T09
#Prof.: Daniel Macedo Batista
def main():
    import random #Para usarmos a biblioteca Random
    semente=int(input("Digite o valor da semente: "))
    random.seed(semente)#Inicializa o gerador de numeros aleatórios
    print("\n==================================================")
    print("             Bem vindo ao Jogo do Bixo!!          ")
    print("==================================================")
    print("Em qual tipo de jogo você deseja apostar?")
    print("   1. milhar   2. trinca   3. grupo   4. sair    5. depurar")
    jogo=int(input(">>>Digite a sua opção (de 1 a 5): "))
    p1=random.randrange(0,10000)#Variaveis randomicas
    p2=random.randrange(0,10000)
    p3=random.randrange(0,10000)
    saldo=0
    depurar=False #bool para depurar
    while jogo!=4:

        if jogo==1:#Jogo 1 Milhar
            if depurar==True:
                print("\n***************************")
                print("INFORMAÇÕES PARA DEPURAÇÃO:")
                print("     OS números sorteados serão:")
                print("1º. %d     2º. %d     3º. %d" %(p1, p2, p3))
            ap=int(input("\nQual o valor que deseja apostar (de R$1 a R$50): "))
            mi=int(input("Entre com o milhar (0 a 9999): "))
            print("\n**************************************************")
            print("Os milhares sorteados foram:")
            print("1º. %d     2º. %d     3º. %d" %(p1, p2, p3))
            print("**************************************************")
            lucro=confere_milhar(mi, p1, p2, p3, ap)
            saldo+=lucro
            if lucro<=0:
                print("\nOBA! Você perdeu os seus R$%d." %(-1*lucro))
            else:
                if mi==p1:
                    print("\nDROGA! Você ganhou o 1o. prêmio: R$%d." %(lucro))
                elif mi==p2:
                    print("\nDROGA! Você ganhou o 2o. prêmio: R$%d." %(lucro))
                else:
                    print("\nDROGA! Você ganhou o 3o. prêmio: R$%d." %(lucro))

            print("\nO seu saldo atual é R$%d" %saldo)

            print("\n--------------------------------------------------")
            print("Em qual tipo de jogo você deseja apostar?")
            print("   1. milhar   2. trinca   3. grupo   4. sair    5. depurar")
            jogo=int(input(">>>Digite a sua opção (de 1 a 5): "))
            p1=random.randrange(0,10000)
            p2=random.randrange(0,10000)
            p3=random.randrange(0,10000)
        elif jogo==2: #Jogo da trinca
            if depurar==True:
                print("\n***************************")
                print("INFORMAÇÕES PARA DEPURAÇÃO:")
                print("     OS números sorteados serão:")
                print("1º. %d     2º. %d     3º. %d" %(p1, p2, p3))
            ap=int(input("\nQual o valor que deseja apostar (de R$1 a R$50): "))
            d1=int(input("Digite a 1a dezena:"))
            d2=int(input("Digite a 2a dezena:"))
            d3=int(input("Digite a 3a dezena:"))
            lucro=confere_trinca(d1, d2, d3, p1, p2, p3, ap)
            saldo+=lucro
            print("\n**************************************************")
            print("Os milhares sorteados foram:")
            print("1º. %d     2º. %d     3º. %d" %(p1, p2, p3))
            print("**************************************************")
            if lucro<=0:
                print("\nOBA! Você perdeu os seus R$%d" %(-1*lucro))
            elif lucro/60==ap:
                    print("\nDROGA! Você ganhou uma trinca: R$%d" %(lucro))
            elif lucro/20==ap:
                    print("\nDROGA! Você ganhou duas dezenas: R$%d" %(lucro))
            elif lucro/10==ap:
                    print("\nDROGA! Você ganhou uma dezena: R$%d" %(lucro))

            print("\nO seu saldo atual é R$%d" %saldo)

            print("\n--------------------------------------------------")
            print("Em qual tipo de jogo você deseja apostar?")
            print("   1. milhar   2. trinca   3. grupo   4. sair    5. depurar")
            jogo=int(input(">>>Digite a sua opção (de 1 a 5): "))
            p1=random.randrange(0,10000)
            p2=random.randrange(0,10000)
            p3=random.randrange(0,10000)
        elif jogo==3: #Jogo dos grupos
            if depurar==True:
                print("\n***************************")
                print("INFORMAÇÕES PARA DEPURAÇÃO:")
                print("     OS números sorteados serão:")
                print("1º. %d     2º. %d     3º. %d" %(p1, p2, p3))
            ap=int(input("\nQual o valor que deseja apostar (de R$1 a R$50): "))
            print("Em qual desses grupos de bixos você deseja apostar?")
            print("1. Civil (00-09)          2. Mecânica (10-19)     3. Mecatrônica (20-29)")
            print("4. Metal\Mat (30-39)      5. Minas (40-49)        6. Naval (50-59)")
            print("7. Petróleo (60-69)       8. Produção (70-79)     9. Quimica (80-89)")
            print("10. Grilo (90-99)")
            gr=int(input("Digite o grupo (1 a 10): "))
            lucro=confere_grupo(gr, p1, p2, p3, ap)
            saldo+=lucro
            print("\n**************************************************")
            print("Os milhares sorteados foram:")
            print("1º. %d     2º. %d     3º. %d" %(p1, p2, p3))
            print("**************************************************")
            if lucro<=0:
                print("\nOBA! Você perdeu os seus R$%d" %(-1*lucro))
            else:
                print("\nDROGA! Você acertou o grupo e ganhou R$%d." %(lucro))
            print("\nO seu saldo atual é R$%d" %saldo)

            print("\n--------------------------------------------------")
            print("Em qual tipo de jogo você deseja apostar?")
            print("   1. milhar   2. trinca   3. grupo   4. sair    5. depurar")
            jogo=int(input(">>>Digite a sua opção (de 1 a 5): "))
            p1=random.randrange(0,10000)
            p2=random.randrange(0,10000)
            p3=random.randrange(0,10000)
        elif jogo==5 and depurar==False:
            depurar=True
            print("\n++++++++++++++++++++++++++++")
            print("MODO DE DEPURAÇÃO FOI LIGADO")
            print("++++++++++++++++++++++++++++")

            print("\nEm qual tipo de jogo você deseja apostar?")
            print("   1. milhar   2. trinca   3. grupo   4. sair    5. depurar")
            jogo=int(input(">>>Digite a sua opção (de 1 a 5): "))
            p1=random.randrange(0,10000)
            p2=random.randrange(0,10000)
            p3=random.randrange(0,10000)
        elif jogo==5 and depurar==True:
            depurar=False
            print("\n+++++++++++++++++++++++++++++++")
            print("MODO DE DEPURAÇÃO FOI DESLIGADO")
            print("+++++++++++++++++++++++++++++++")

            print("\nEm qual tipo de jogo você deseja apostar?")
            print("   1. milhar   2. trinca   3. grupo   4. sair    5. depurar")
            jogo=int(input(">>>Digite a sua opção (de 1 a 5): "))
            p1=random.randrange(0,10000)
            p2=random.randrange(0,10000)
            p3=random.randrange(0,10000)
        else:
            jogo=4

    print("\n\nSaldo final = R$%d." %saldo)
    print("\nObrigado por jogar o Jogo do Bixo!!!")


#============================================================

def confere_milhar(mi, p1, p2, p3, ap):
    ''' (int, int, int, int, int) -> int
    Recebe o valor mi do milhar apostado, os 3 milhares sorteados (p1, p2, p3)
    e o valor ap apostado. A função deve retornar o valor ganho ou perdido
    ao jogar no milhar. Caso o milhar mi seja igual ao 1o, 2o, ou 3o premios a funÃ§Ã£o
    retorna 300*ap, 200*ap ou 100*ap, ou retorna -ap caso contrário.'''
    saldo=ap
    if mi==p1:
        saldo*=300
    elif mi==p2:
        saldo*=200
    elif mi==p3:
        saldo*=100
    else:
        saldo*=-1
    return saldo

#============================================================

def confere_trinca(d1, d2, d3, p1, p2, p3, ap):
    ''' (int, int, int, int, int, int, int) -> int

    Recebe 3 dezenas apostadas (d1, d2, d3), os 3 milhares sorteados (p1, p2, p3)
    e o valor ap apostado. A função deve retornar o valor ganho ou perdido
    ao jogar na trinca. Caso as 3 dezenas estejam corretas, a função retorna
    60*ap, caso 2 dezenas estejam corretas, a função retorna 20*ap, e caso
    uma dezena esteja correta, a função retorna 10*ap. Caso nenhuma dezena
    esteja correta, a função retorna -ap.'''
    saldo=ap
    cont=0 #variavel para contar as vezes que ganhou
    p1=p1%100
    p2=p2%100
    p3=p3%100
    if d1==p1 or d1==p2 or d1==p3:
        cont+=1
    if d2!=d1 and (d2==p1 or d2==p2 or d2==p3):
        cont+=1
    if (d3!=d2 or d3!=d1) and (d3==p1 or d3==p2 or d3==p3):
        cont+=1
#..........................................................
    if cont==3:
        saldo*=60
    elif cont==2:
        saldo*=20
    elif cont==1:
        saldo*=10
    else:
        saldo*=-1
    return saldo

#===========================================================

def confere_grupo(gr, p1, p2, p3, ap):
    ''' (int, int, int, int, int) -> int

    Recebe o numero de um grupo gr (1 a 10) apostado, os 3 milhares sorteados
    (p1, p2, p3) e o valor ap apostado. A função deve retornar o valor ganho
    ou perdido ao jogar no grupo. A lista abaixo indica o numero,
    o nome e o intervalo de cada grupo válido:'''
    saldo=ap
    p1=(p1%100)//10
    p2=(p2%100)//10
    p3=(p3%100)//10
    gr=gr-1
    if gr==p1 or gr==p2 or gr==p3:
        saldo*=2
    else:
        saldo*=-1
    return saldo
#============================================================
main()