# -*- coding: utf-8 -*-
"""jogo da forca

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZj9DOFNNsuPg67AjJ6N8JDo65q75zBa
"""

print('**********************')
print('***Bem vindo ao jogo da Forca!***')
print('**********************')
palavra_secreta = str(input("digite uma palavra:")).upper()
cont = len(palavra_secreta)
letras_acertadas = []
for i in range(cont):
  letras_acertadas.append("_")
print(letras_acertadas)
acertou = False
enforcou = False
erros = 0
while(not acertou and not enforcou):
  chute = input("Qual letra?").upper()
  if(chute in palavra_secreta):
    posicao = 0
    for letra in palavra_secreta:
      if chute == letra:
        letras_acertadas[posicao] = letra
      posicao = posicao + 1
  else:
    erros += 1 #erros = erros + 1
  acertou='_' not in letras_acertadas
  enforcou = (erros == 6)
  print(letras_acertadas)
if(acertou):
  print('\nVocê ganhou!')
else:
  print('\nVocê perdeu!')
print('Fim do jogo')

import ipywidgets as widgets
from IPython.display import display, clear_output

FASES = [
    # 0 erros - boneco completo
    """
       -----
       |   |
       |   O
       |  /|\\
       |  / \\
       |
    --------
    """,
    # 1 erro - perna direita some
    """
       -----
       |   |
       |   O
       |  /|\\
       |  /
       |
    --------
    """,
    # 2 erros - perna esquerda some
    """
       -----
       |   |
       |   O
       |  /|\\
       |
       |
    --------
    """,
    # 3 erros - braço direito some
    """
       -----
       |   |
       |   O
       |  /|
       |
       |
    --------
    """,
    # 4 erros - braço esquerdo some
    """
       -----
       |   |
       |   O
       |   |
       |
       |
    --------
    """,
    # 5 erros - corpo some
    """
       -----
       |   |
       |   O
       |
       |
       |
    --------
    """,
    # 6 erros - cabeça some
    """
       -----
       |   |
       |
       |
       |
       |
    --------
    """,
]

# Estado do jogo
estado = {
    "palavra_secreta": "",
    "letras_acertadas": set(),
    "letras_erradas": set(),
    "erros": 0,
    "max_erros": 6,
    "fase": "configurar",  # configurar ou jogar
}

# ── Widgets ──────────────────────────────────────────────
saida = widgets.Output()

# Tela de configuração
input_palavra = widgets.Password(placeholder="Digite a palavra secreta...", layout=widgets.Layout(width="300px"))
btn_iniciar   = widgets.Button(description="Iniciar Jogo", button_style="success")

# Tela de jogo
forca_txt    = widgets.Textarea(rows=9, layout=widgets.Layout(width="220px"), disabled=True)
palavra_txt  = widgets.Label()
erradas_txt  = widgets.Label()
tentativas_txt = widgets.Label()
input_letra  = widgets.Text(placeholder="Digite uma letra...", layout=widgets.Layout(width="180px"))
btn_chutar   = widgets.Button(description="Chutar", button_style="primary")
mensagem_txt = widgets.Label()
btn_reiniciar = widgets.Button(description="Jogar Novamente", button_style="warning",
                               layout=widgets.Layout(display="none"))

# ── Funções ───────────────────────────────────────────────
def atualizar_tela():
    forca_txt.value       = FASES[estado["erros"]]
    restantes             = estado["max_erros"] - estado["erros"]
    tentativas_txt.value  = f"⚡ Tentativas restantes: {restantes}"

    # Monta display da palavra
    display_palavra = " ".join(
        letra if letra in estado["letras_acertadas"] else "_"
        for letra in estado["palavra_secreta"]
    )
    palavra_txt.value = f"📝 Palavra: {display_palavra}"

    # Letras erradas
    if estado["letras_erradas"]:
        erradas_txt.value = "❌ Letras erradas: " + ", ".join(sorted(estado["letras_erradas"]))
    else:
        erradas_txt.value = "❌ Letras erradas: nenhuma ainda"


def verificar_vitoria():
    return all(l in estado["letras_acertadas"] for l in estado["palavra_secreta"])


def iniciar_jogo(b):
    palavra = input_palavra.value.upper().strip()
    if not palavra or not palavra.isalpha():
        with saida:
            clear_output()
            print("⚠️ Digite uma palavra válida (apenas letras)!")
        return

    # Reseta estado
    estado["palavra_secreta"]  = palavra
    estado["letras_acertadas"] = set()
    estado["letras_erradas"]   = set()
    estado["erros"]            = 0
    estado["fase"]             = "jogar"

    mensagem_txt.value           = ""
    btn_reiniciar.layout.display = "none"
    input_letra.disabled         = False
    btn_chutar.disabled          = False
    input_letra.value            = ""

    atualizar_tela()

    with saida:
        clear_output()
        display(painel_jogo)


def chutar(b):
    chute = input_letra.value.upper().strip()
    input_letra.value = ""

    if len(chute) != 1 or not chute.isalpha():
        mensagem_txt.value = "⚠️ Digite apenas UMA letra válida!"
        return

    if chute in estado["letras_acertadas"] or chute in estado["letras_erradas"]:
        mensagem_txt.value = "⚠️ Você já tentou essa letra!"
        return

    if chute in estado["palavra_secreta"]:
        estado["letras_acertadas"].add(chute)
        mensagem_txt.value = "✅ Boa! A letra está na palavra!"
    else:
        estado["letras_erradas"].add(chute)
        estado["erros"] += 1
        mensagem_txt.value = "💨 Errou! Uma parte do boneco desapareceu..."

    atualizar_tela()

    if verificar_vitoria():
        mensagem_txt.value           = f"🎉 PARABÉNS! Você adivinhou: {estado['palavra_secreta']}"
        input_letra.disabled         = True
        btn_chutar.disabled          = True
        btn_reiniciar.layout.display = ""

    elif estado["erros"] >= estado["max_erros"]:
        mensagem_txt.value           = f"💀 O boneco desapareceu! A palavra era: {estado['palavra_secreta']}"
        input_letra.disabled         = True
        btn_chutar.disabled          = True
        btn_reiniciar.layout.display = ""


def reiniciar(b):
    with saida:
        clear_output()
        input_palavra.value = ""
        display(painel_config)


# ── Eventos ───────────────────────────────────────────────
btn_iniciar.on_click(iniciar_jogo)
btn_chutar.on_click(chutar)
btn_reiniciar.on_click(reiniciar)

# Permite chutar com Enter
def chutar_enter(widget):
    chutar(None)

input_letra.on_submit(chutar_enter)

# ── Painéis ───────────────────────────────────────────────
painel_config = widgets.VBox([
    widgets.HTML("<h2>🪢 Jogo da Forca</h2>"),
    widgets.HTML("<b>Digite a palavra secreta:</b>"),
    input_palavra,
    btn_iniciar,
])

painel_jogo = widgets.VBox([
    widgets.HTML("<h2>🪢 Jogo da Forca</h2>"),
    widgets.HBox([
        forca_txt,
        widgets.VBox([
            palavra_txt,
            erradas_txt,
            tentativas_txt,
            widgets.HBox([input_letra, btn_chutar]),
            mensagem_txt,
            btn_reiniciar,
        ])
    ])
])

# ── Iniciar ───────────────────────────────────────────────
with saida:
    display(painel_config)

display(saida)