# -*- coding: utf-8 -*-
"""jogo do Nim

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMKmhUMUd5QFllfpjMEPvKaYIpaZjSL8
"""

import random  #puxa o random para criar aleatoridade nas dificuldades.

def escolher_dificuldade(): #escolhe a dificuldade para tornar o jogo mais justo.
    while True:
        print("\nEscolha a dificuldade:")
        print("1 - Fácil")
        print("2 - Médio")
        print("3 - Difícil")

        opcao = input("Digite a opção: ")

        if opcao == "1":
            return "facil"
        elif opcao == "2":
            return "medio"
        elif opcao == "3":
            return "dificil"
        else:
            print("Opção inválida. Tente novamente.")

def computador_escolhe_jogada(n, m, dificuldade):
    if dificuldade == "facil":
        return random.randint(1, min(m, n)) #joga aleatoriamente de 1 ao maior numero permitido.

    elif dificuldade == "medio":
        # 50% de chance de errar
        if random.random() < 0.5:
            return random.randint(1, min(m, n))

    jogada = n % (m + 1)  # Tenta deixar um múltiplo de (m+1) para o jogador, assim o deixando em uma posição de derrota.
    if jogada == 0:
      return min(m, n)
    return jogada

def usuario_escolhe_jogada(n, m):
    while True:         #faz o programa pedir novamente até o usuário digitar algo correto. "loop"
        try:            #garante que o input é um número inteiro (não texto)
            jogada = int(input(f"Quantas peças você vai tirar? (1 até {min(m, n)}): "))
            if 1 <= jogada <= min(m, n):
                return jogada
            else:
                print("Jogada inválida. Tente novamente.")
        except ValueError:
            print("Por favor, digite um número inteiro.")

def partida():
    print("--- JOGO DO NIM (QUEM TIRA A ÚLTIMA GANHA) ---")

    dificuldade = escolher_dificuldade()    #coloca a dificuldade esscolhida

    while True:          #novamente em loop até for correto
        try:
            n = int(input("\nQuantas peças no total? "))   #define o total de peças
            if n > 0:            # o numero tem que ser maior que zero
                break
            print("Digite um número maior que zero.")
        except ValueError:
            print("Valor inválido.")

    while True:            #novamente em loop até for correto
        try:
            m = int(input("Limite de peças por jogada? ")) #define o limite de peças
            if m > 0:     # o numero tem que ser maior que zero
                break
            print("Digite um número maior que zero.")
        except ValueError:
            print("Valor inválido.")

    print(f"\nDificuldade escolhida: {dificuldade.upper()}")

    # Define quem começa com a mesma lógica matemática onde se n for multiplo de (m+1) quem começa está em desvantagem.
    if n % (m + 1) == 0:
        print("Você começa!")
        vez_do_computador = False
    else:
        print("O computador começa!")
        vez_do_computador = True

    # Loop principal do jogo, fica rodando até as peças acabarem. A cada rodada subtrai a jogada do total (n).
    while n > 0:
        if vez_do_computador:
            jogada = computador_escolhe_jogada(n, m, dificuldade)
            print(f"\nO computador tirou {jogada} peça(s).")
        else:
            jogada = usuario_escolhe_jogada(n, m)
            print(f"\nVocê tirou {jogada} peça(s).")

        n -= jogada
        print(f"Restam {n} peça(s) no tabuleiro.")

        vez_do_computador = not vez_do_computador # Alterna os turnos. "repetição"

    # Resultado final aqui funciona ao contrário como em cima no final ele inverte para a vez do computador, então n = 0 ou seja o jogador tirou a última.
    if vez_do_computador:
        print("\nFim de jogo! 🎉 Você ganhou!")
    else:
        print("\nFim de jogo! 💻 O computador ganhou!")

# Executa o jogo
partida()