# -*- coding: utf-8 -*-
"""atividade P

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfXm97gl-OnRxctypGwjISTEO2ClWY02
"""

import yfinance as yf
import matplotlib.pyplot as plt
def correlacao(acao1, acao2):
 d1 = yf.download(acao1, start="2023-01-01")["Close"]
 d2 = yf.download(acao2, start="2023-01-01")["Close"]
 dados = d1.join(d2, lsuffix='_1', rsuffix='_2').dropna() # tive que tirar o .to_frame() para funcionar. porque?
 return dados
dados = correlacao("PETR4.SA", "VALE3.SA")
plt.scatter(dados.iloc[:,0], dados.iloc[:,1])
plt.title("Correlação PETR4 x VALE3")
plt.xlabel("PETR4")
plt.ylabel("VALE3")
plt.show()