# -*- coding: utf-8 -*-
"""aula08/04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16EGrfGxNIGun5CQmxf5cGDafM_m9s0fr
"""

import numpy as np
import plotly.graph_objects as go
np.random.seed(42)
V0 = 1000
r = 0.001
vol = 0.02
T = 200
valores = [V0]
for t in range(1, T):
 V_atual = valores[-1]
 ruido = np.random.normal(0, vol)
 V_novo = V_atual * (1 + r + ruido)
 valores.append(V_novo)
fig = go.Figure()
fig.add_trace(go.Scatter(y=valores,mode='lines',name='Valor do Investimento'))
fig.update_layout(title='Simulação de Investimento com Risco',
xaxis_title='Tempo (dias)', yaxis_title='Capital (R$)')
fig.show()

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import yfinance as yf
ativos = ["ITUB4.SA", "BBDC4.SA", "BBAS3.SA", "SANB11.SA"]
dados = yf.download(ativos, start="2022-01-01", end="2024-01-01")['Close']
retornos = dados.pct_change().dropna()
np.random.seed(42)
capital_inicial = 10000
pesos = np.array([0.25, 0.25, 0.25, 0.25])
retorno_carteira = retornos.dot(pesos)
valores = [capital_inicial]
for r in retorno_carteira:
 novo_valor = valores[-1] * (1 + r)
 valores.append(novo_valor)
fig = go.Figure()
for ativo in ativos:
 fig.add_trace(go.Scatter(y=dados[ativo] / dados[ativo].iloc[0] * capital_inicial,
mode='lines', name=ativo))
fig.add_trace(go.Scatter(y=valores, mode='lines', name='Carteira Bancos',
line=dict(width=4) ))
fig.update_layout( title='Simulação de Investimento em Bancos Brasileiros',
xaxis_title='Tempo',
 yaxis_title='Valor (R$)')
fig.show()