# -*- coding: utf-8 -*-
"""aula29/04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EYBKnVelPhVXoja7UPtu1n1fPE4fZNHi
"""

from openpyxl import Workbook, load_workbook
ARQUIVO = "financeiro.xlsx"

def criar_planilha():
  wb = Workbook()
  ws = wb.active
  ws.title = "investimentos"
  #cabeçalho
  ws.append(["Cliente","Valor inicial","Taxa (%)","Meses","Valor Futuro"])
  #Dados exemplo
  ws.append(["Ana",1000, 1.5,12,""])
  ws.append(["Joâo",2000,2.0,10,""])
  ws.append(["Maria",1500,1.2,8,""])
  wb.save(ARQUIVO)
  print("Planilha criada!")

def calcular_financeiro():
  wb = load_workbook(ARQUIVO)
  ws = wb["investimentos"]
  for linha in ws.iter_rows(min_row=2):
   nome = linha[0].value
   VP = linha[1].value
   taxa = linha[2].value/100
   meses = linha[3].value
   #fórmula
   VF = VP*(1+taxa)**meses
   #grava na planilha
   linha[4].value = round(VF,2)
  wb.save(ARQUIVO)
  print("Cálculo realizado e salvo!")

def mostrar_planilha():
  wb = load_workbook(ARQUIVO)
  ws = wb["investimentos"]
  for linha in ws.iter_rows(values_only=True):
    print(linha)
criar_planilha()
calcular_financeiro()
mostrar_planilha()

