# -*- coding: utf-8 -*-
"""aula06/05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1isF-k67QQTZD5NQASHFmHUDQLXuCYADY
"""

import openpyxl
from openpyxl import load_workbook
def adicionar_aluno(planilha):
  print("\n---Adicionar Novo Aluno---")
  nome = input("digite o nome do aluno:")
  curso = input("digite o curso:")
  area = input("Digite a área:")
  while True:
    try:
      semestre=int(input("Digite o semestre (apenas números)"))
      break
    except ValueError:
      print("Erro: por favor, digite um número válido para o semestre.")
  nova_linha = [nome,curso,area,semestre]
  planilha.append(nova_linha)
  print(f"\n✓ Aluno(a)'{nome}'adicionado(a) com sucesso!")
def editar_celula(planilha):
  print("\n----Editar Aluno---")
  nome_aluno = input("Digite o nome do aluno que deseja editar:")
  linha_aluno = None
  for i in range(2, planilha.max_row + 1):
    if planilha.cell(row=i, column=1).value == nome_aluno:
      linha_aluno = i
      break
  if not linha_aluno:
    print(f"Aluno(a) '{nome_aluno}' não encontrado(a).")
    return
  print("\nQual a informação você quer editar?")
  print("1 - Nome")
  print("2 - Curso")
  print("3 - Área")
  print("4 - Semestre")

  while True:
    try:
      coluna = int(input("Digite o número da coluna para editar:"))
      if 1<= coluna <= 4:
       break
      else:
       print("Opção invalida. Escolha um número entre 1 e 4.")
    except ValueError:
      print("Por favor, digite um número.")
  novo_valor = input(f"Digite o novo valor:")
  if coluna == 4:
    try:
      novo_valor = int(novo_valor)
    except ValueError:
      print("Semestre deve ser um número. A alteração falhou.")
      return
  planilha.cell(row=linha_aluno, column=coluna).value = novo_valor
  print(f"\n Dados de '{nome_aluno}' atualizados com sucesso!")
def apagar_aluno(planilha):
  print("\n----Apagar Aluno---")
  nome_aluno = input("Digite o nome do aluno que deseja apagar:")
  linha_aluno = None
  for i in range(2, planilha.max_row + 1):
    if planilha.cell(row=i, column=1).value == nome_aluno:
      linha_aluno = i
      break
  if linha_aluno:
    planilha.delete_rows(linha_aluno)
    print(f"\nAluno(a) '{nome_aluno}' apagado(a) com sucesso!")
  else:
    print(f"\nAluno(a) '{nome_aluno}' não encontrado(a para apagar.)")

def listar_alunos(planilha):
  print("\n"+"="*70)
  print("---LISTA DE ALUNOS ATUAL---")
  #Garante que o cabeçalho não quebre se houver None
  cabeçalho = [str(celula.value or"") for celula in planilha[1]]
  print(f"{cabeçalho[0]:20} | {cabeçalho[1]:<20} | {cabeçalho[2]:<15} | {cabeçalho[3]}")
  print("-"*70)
  for linha in planilha.iter_rows(min_row=2, values_only=True):
   #Converte valores None para strings vazias para evitar erro de formatação
   nome = str(linha[0] or "")
   curso = str(linha[1] or "")
   area = str(linha[2] or "")
   semestre = str(linha[3] or "N/A")
   print(f"{nome:<20}| {curso:<20} | {area:<15} | {semestre}")
  print("="*70 + "\n")

def menu_principal():
  caminho = "cursos.xlsx"
  try:
    pasta_cursos = load_workbook(caminho)
    planilha = pasta_cursos.active
    print(f"Arquivo '{caminho}' carregado com sucesso")
  except FileNotFoundError:
    print(f"ERRO: Arquivo '{caminho}' não encontrado. Execute a célula de upload (Passo 1) primeiro.")
    return
  while True:
    print("\n---MENU DE OPÇÕES---")
    print("1 - Listar todos os alunos")
    print("2 - Adicionar novo aluno")
    print("3 - Editar um aluno")
    print("4 - Apagar um aluno")
    print("5 - Salvar e Sair")
    escolha = input(">>Digite o número da sua escolha:")
    if escolha == '1':
      listar_alunos(planilha)
    elif escolha == '2':
      adicionar_aluno(planilha)
    elif escolha == '3':
      editar_celula(planilha)
    elif escolha == '4':
      apagar_aluno(planilha)
    elif escolha == '5':
      caminho_salvar = "cursos_modificado.xlsx"
      pasta_cursos.save(caminho_salvar)
      print(f"\nAlterações salvas com sucesso no arquivo: '{caminho_salvar}'")
      print("Saindo do programa. Execute o Passo 3 para fazer o download.")
      break
    else:
      print("\nOpção inválida | Por favor, escolha um número de 1 a 5.")
menu_principal()

from google.colab import files
print("Por favor, selecione o arquivo 'cursos.xlsx do seu computador")
uploaded = files.upload()
# Confirma que o arquivo foi carregado
if 'cursos.xlsx' in uploaded:
 print("\nArquivo 'cursos.xlsx' carregado com sucesso!")
else:
 print("\nO arquivo não foi carregado. Tente rodar a célula novamente.")